name: 'Changelog from Conventional Commits'
description: 'Generate and update the CHANGELOG from conventional commits since latest tag or from a given tag range'
author: Nicolas Giard
inputs:
  token:
    description: GitHub Token
    required: true
  tag:
    description: The latest tag (which triggered this job) (only if using latest tag)
    required: false
  fromTag:
    description: The tag from which the changelog is to be determined (only if using tag range)
    required: false
  toTag:
    description: The tag up to which the changelog is to be determined (only if using tag range)
    required: false
  excludeTypes:
    description: Types to exclude from the Changelog
    required: false
    default: build,docs,other,style
  writeToFile:
    description: Should CHANGELOG.md be updated with latest changelog
    required: false
    default: 'true'
  includeRefIssues:
    description: Should the changelog include the issues referenced for each PR.
    required: false
    default: 'true'
  useGitmojis:
    description: Prepend type headers with their corresponding gitmoji
    required: false
    default: 'true'
  includeInvalidCommits:
    description: Whether to include commits that don't respect the Conventional Commits format
    required: false
    default: 'false'
  formatForSlack:
    description: Whether to format for slack which has it's own kind of markdown formatting
    required: false
    default: 'false'
outputs:
  changes:
    description: Generated changelog
  changesForSlack:
    description: Generated changelog formatted for slack (only when formatForSlack is set to true)
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: wind
  color: red
